Repository Likelion-at-SMWU-11th/LoveBridge-Server, pull requests merged in 2023-08, with the labels that each got.

#15 [Feat] 마이페이지 서류등록 구현 (#10)
  love_bridge/settings.py
  love_bridge/urls.py
  mypage/__init__.py
  mypage/admin.py
  mypage/apps.py
  mypage/forms.py
  mypage/migrations/0001_initial.py
  mypage/migrations/0002_rename_attached_document_imgfile.py
  mypage/migrations/__init__.py
  mypage/models.py
  mypage/serializers.py
  mypage/templates/documents.html
  mypage/templates/programs.html
  mypage/tests.py
  mypage/urls.py
  mypage/views.py
Labels: Feature

#18 [Feat] 실시간 인기글 조회 (#14)
  love_bridge/settings.py
  love_bridge/urls.py
  love_bridge/views.py
  posts/admin.py
  posts/management/commands/create_dummy.py
  posts/migrations/__init__.py
  posts/models.py
  posts/serializers.py
  posts/urls.py
  posts/views.py
Labels: Feature

#19 [Feat] 전체글 조회 (#17)
  posts/urls.py
  posts/views.py
Labels: Feature

#21 [Feat] 마감임박글 조회 구현
  posts/serializers.py
  posts/urls.py
  posts/views.py
Labels: Feature

#22 [Fix] 충돌 해결
  love_bridge/urls.py
  posts/management/commands/create_dummy.py
  posts/urls.py
Labels: bug

#27 [Feat] 프로그램 검색 (#26)
  posts/views.py
Labels: Feature

#31 [Feat] 찜한 프로그램 가져오기 (#28)
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
Labels: Feature

#35 [Feat] 프로그램 신청 (#33)
  love_bridge/settings.py
  posts/migrations/0002_program_registered_users.py
  posts/migrations/0003_alter_program_registered_users.py
  posts/models.py
  posts/templates/detail.html
  posts/templates/programs.html
  posts/urls.py
  posts/views.py
Labels: Feature

#38 [Chore] Postman 테스트 후 전반적인 코드 수정 (#36)
  love_bridge/settings.py
  love_bridge/urls.py
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
  programs/admin.py
  programs/management/commands/create_dummy.py
  programs/migrations/0002_remove_program_registered_users.py
  programs/models.py
  programs/serializers.py
  programs/templates/detail.html
  programs/templates/programs.html
  programs/urls.py
  programs/views.py
Labels: Enhanced

#40 [Chore] 소셜 로그인시 유저 정보 저장 (#39)
  accounts/forms.py
  accounts/migrations/0001_initial.py
  accounts/migrations/__init__.py
  accounts/models.py
  accounts/templates/index.html
  accounts/urls.py
  accounts/views.py
  love_bridge/settings.py
  programs/views.py
Labels: Enhanced

#42 [Chore] 카카오 로그아웃 구현 시도 (#2)
  programs/migrations/0002_alter_program_applicant.py
Labels: Enhanced

#45 [Chore] 더미 데이터 쌓고 이에 맞게 모델 수정 (#44)
  accounts/migrations/0001_initial.py
  mypage/migrations/0001_initial.py
  programs/management/commands/create_dummy.py
  programs/migrations/0001_initial.py
  programs/models.py
  programs/serializers.py
  programs/views.py
Labels: Enhanced

#46 [Chore] 프론트와 연동 후 코드 수정 (#43)
  mypage/migrations/0002_remove_mydocument_user_alter_mydocument_file1_and_more.py
  mypage/models.py
  mypage/serializers.py
  mypage/urls.py
  mypage/views.py
  programs/management/commands/create_dummy.py
  programs/migrations/0001_initial.py
  programs/migrations/0002_remove_myprogram_process.py
  programs/models.py
  programs/urls.py
  programs/views.py
  requirements.txt
Labels: Enhanced
